### ISSUE TITLE
parameter doesn't match mapping

### ISSUE THREAD

**Issue by devosb** [silnrsi/silconverters#10]
A user reported an issue by sending the screen shot below.
![mismatch](https://user-images.githubusercontent.com/12450072/145114004-2ec98b67-053b-4ca9-b675-1dae3578cf8f.png)

**Comment by bobeaton** [comment]
Not sure what the issue might have been, but given that it's "SIL Converters for Office", and Word, for example, communicates in a wide format (e.g. UTF 16 or widened legacy encoding or widened symbol font data), if the converter (s)he was trying to use outputted in a byte (non-wide) format, it might not work.
