### ISSUE TITLE
Installers do not seem to be signed

### ISSUE THREAD

**Issue by devosb** [silnrsi/silconverters#14]
The installers for [SIL Converters](https://software.sil.org/silconverters/) v5.1 (released in January) do not seem to be signed. These installers are build with GitHub Actions, and I thought signed by TeamCity.
![silconverters](https://user-images.githubusercontent.com/12450072/230490157-fb55a620-13c8-4352-bb6b-fe871ce83538.png)

**Comment by devosb** [comment]
The pinned buildon TeamCity, the [GitHub release](https://github.com/silnrsi/silconverters/releases/tag/v5.1), and the downloads on the product site are all the same (sha256). Note the product site has links in the middle to both the x86 and x64 installers, the link at the top of the page in a sidebar is just for the x64 installer.

**Comment by devosb** [comment]
I am confused. Right clicking on the installers and selecting properties shows they are signed. In my Windows Insiders VM (which is somewhere between Windows 10 and Windows 11) and in my Windows 10 VM (updated, but no Insiders program) I see the screenshot above.

**Comment by devosb** [comment]
But if I select Properties, and look at the details of the certificate, and then run the installer, Windows thinks it is signed.

**Comment by devosb** [comment]
And doing so, on either the x86 or x64 installer, also makes the other installer work.

**Comment by devosb** [comment]
@papeh writes that the way the installer is built, it needs to be signed twice for Windows to trust it:
- the .msi must be signed
- the .exe installer that contains the .msi must be signed

If it is signed after the fact (as I imagine is happening), only the .exe will be signed, so the properties will show the signature, but Windows will show the yellow dialog you saw.

Looking at [the GHA workflow](https://github.com/silnrsi/silconverters/blob/master/.github/workflows/build.yml), I see no step to publish artifacts, which is fine, since we don't support signing on GHA.

**Comment by devosb** [comment]
@bobeaton writes the exes that are uploaded to the website are from the team city build; not GHA.
So again if you look at the log for the latest build in team City, and it looks like sign both the MSI and the exe, which is what I thought I saw, then I think it's signed. It's just for some reason it doesn't show that way inside of VM... Not sure why

**Comment by bobeaton** [comment]
The *.msi and the *.exe are both signed. But they don't show as signed when run from within a VM (not for me either)... but if you run the installer on a real machine, they show as signed.

i'm not sure how to debug that further

**Comment by bobeaton** [comment]
FYI, after a recent update in my VM, they now show as signed in VMs... must have been a Windows VM thing
