### ISSUE TITLE
Cannot use arrow keys in Word

### ISSUE THREAD

**Issue by jkornelsen** [silnrsi/silconverters#2]
_Quotes from an email:_

The "Uni-consistent-spellchecker" won't allow you to use arrow keys in Word. Can the uni-consistent-arrow-key-blocker be removed, fixed, or at least made a non-default option in the installer in the next release?

With that "shortcut" we saved a few people some keystrokes, but ended up hamstringing the rest of the population!

**Comment by bobeaton** [comment]
Yes it can (whenever that might be), have you been able to disable it?

I think it gets enabled by default bkz we install it in this folder:

C:\Users\pete_\AppData\Roaming\Microsoft\Templates (where pete_ is the username)

Different versions of Word have different ways of enabling/disabling Add-ins (it’s a COM Add-in, IINM), but worst case, you can just remove the file from this folder and it won’t be automatically loaded and enabled anymore.

UPDATE: it may not be in that folder… just do a search from “C:\Users\pete_\AppData\Roaming\Microsoft” for *.dot files, and it’ll show somewhere…

Bob
