### ISSUE TITLE
Can the wrong bitness installer proceed with setup?

### ISSUE THREAD

**Issue by devosb** [silnrsi/silconverters#5]
The installer will check for the bitness of Office, and if there is a mismatch (say 32 installer and 64 bit Office), the install option _SIL Converters for Office_ will be un-selected. That is good. If I select that option anyway, the installer seems to complete. I presume that feature will not work. Is that ability to override intentional?

**Comment by bobeaton** [comment]
yes, bkz maybe they will subsequently install the same bitness of Office and then it would work. (although, from the way the Bulk Word Document converter feature _used_ to be described, it's possible that it would work even w/ the wrong bitness of Office installed... but a) I haven't tested this and b) definitely not w/ "SILConverters for Office").
