### ISSUE TITLE
Different number of entries for SIL Converters for Office options depending on bitness

### ISSUE THREAD

**Issue by devosb** [silnrsi/silconverters#6]
If the installer does not match the bitness of Office, then there seems to be two entries
- SILConverters for Office 2013
- SILConverters for Office 2016/2019/365

not just one
- SILConverters for Office 2016/2019/365

**Comment by bobeaton** [comment]
underlyingly, there's no difference in the package for SILConverters for Office between office 2013/16/19/365, but they do get their 'bitness' indication from different places (2013 in one place and one place for the other 3).

Mostly this message is just indicating what version of Office was actually found on the machine. So unless you're saying that you saw both of these feature options in a single installation, only one of them would be shown at a time.
