### ISSUE TITLE
Installer says Office plugins support only 2016/2019/365

### ISSUE THREAD

**Issue by devosb** [silnrsi/silconverters#7]
Both installers, when looking at the options for _SILConverters for Office_, seems to indicate supporting 2016/2019/365. This indication is both in the small explanation screen on the right of the installer, and in the menu option (you need to scroll to the right or use the hover over tooltip) to see all the text of the menu option. @bobeaton says it should support Office back to 2003. If so, can the installer text be improved? Below are two screen shots (the filename, showing the bitness, is below the images)

![sil_converters_for_office_x86](https://user-images.githubusercontent.com/12450072/145112535-c06301cb-048f-4c46-9007-f996964f9992.png)
`Sil_converters_for_office_x86.png`

![sil_converters_for_office_x64](https://user-images.githubusercontent.com/12450072/145112647-307b05aa-4b38-438e-aa1f-33391cc74fd3.png)
`Sil_converters_for_office_x64.png`

**Comment by devosb** [comment]
This testing was done on 1 Oct 2021, so maybe the issue has been fixed by now.

**Comment by bobeaton** [comment]
changed the text to read: 
"Works with Word 2010, 13, 16, 19, or 365" (for the x64 installer) and 
"Works with Office 2003, 07, 10, 13, 16, 19, or 365" (for the x86 installer)
(due out in the forthcoming 5.1.1.0 release)
