### ISSUE TITLE
Bulk Word Document Converter only supports through 2013?

### ISSUE THREAD

**Issue by devosb** [silnrsi/silconverters#8]
Both installers, when looking at the options for _Bulk Word Document Converter_ , seems to indicate supporting only though 2013. This indication is both in the small explanation screen on the right of the installer, and in the menu option (you need to scroll to the right or use the hover over tooltip) to see all the text of the menu option. @bobeaton says I’ll test this, but it should support any version from 2003 (or 2016++ if x64 is installed). If so, can the installer text be improved? Below are two screen shots (the filename, showing the bitness, is below the images)

![bulk_word_document_converter_x86](https://user-images.githubusercontent.com/12450072/145113049-c29858c2-ddb0-4fbe-b99a-c205b99f9f56.png)
`Bulk_word_document_converter_x86.png`

![bulk_word_document_converter_x64](https://user-images.githubusercontent.com/12450072/145113073-060a48cc-3fb4-49ea-9a04-3c254aa7554c.png)
`Bulk_word_document_converter_x64.png`

**Comment by devosb** [comment]
This testing was done on 1 Oct 2021, so maybe the issue has been fixed by now.

**Comment by bobeaton** [comment]
this should be fixed in the next release 5.1.3 (probably listed as 5.1 on the webpage)
