### ISSUE TITLE
Where does the number 5.0.0.1 come from?

### ISSUE THREAD

**Issue by devosb** [silnrsi/silconverters#9]
The version number for this release is 5.0, yet when using the installer the number 5.0.0.1 flashes briefly on the screen. Where does this number come from?

**Comment by bobeaton** [comment]
The 5.0 is the truncated version number and the 5.0.0.1 is the full version number. We might go thru several of the final two digits before changing the major (truncated) version number.
The major (truncated) version number changes only when something breaking changes...
